name: Deploy Dialogflow

on:
  push:
    branches: 
      - master
    paths:
      - '**/dialogflow.js'

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm ci
        working-directory: ./functions
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} 
