name: Deploy Web-hook

on:
  push:
    branches: 
      - master
    paths:
      - '**/webhook.js'

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm ci
        working-directory: ./web-hook/functions
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions:webhook
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
